const $=x=>document.getElementById(x),palavras={
facil:['casa','jogo','livro','amigo','escola','codigo','robot','pizza','bolo','arroz','gato','cachorro','planeta','estrela','lapis','caneta','praia','jardim','banana','queijo'],
medio:['algoritmo','programacao','inteligencia','informacao','comunicacao','computacao','criptografia','engenharia','astronomia','laboratorio','experimento','matematica','estatistica','geometria','ecossistema','civilizacao','democracia','diversidade','patrimonio','cartografia','sustentabilidade','arqueologia','dicionario','interpretacao','criatividade','imaginacao','literatura','biblioteca','aprendizagem','curiosidade','responsabilidade','colaboracao','investigacao','raciocinio','conhecimento','biodiversidade','constelacao','atmosfera','temperatura','vegetacao','decodificador','transmissao','sequencia','combinacao','codificacao','decifracao','pontuacao','multiplicador','algoritmo inteligente','codigo misterioso','planeta distante','biblioteca digital','mensagem secreta','ciencia divertida','tecnologia criativa','sistema complexo','universo infinito','futuro sustentavel','robot curioso','descoberta importante','matematica aplicada','floresta tropical','sinal desconhecido'],
dificil:['o algoritmo encontrou respostas','a tecnologia muda tudo','decodifique a mensagem secreta','o universo guarda misterios','aprender codigo e divertido','a ciencia explica fenomenos','nosso planeta precisa cuidado','o robot encontrou um sinal','computadores processam informacoes rapidamente','a biblioteca possui muitos livros','descubra a combinacao correta','o sistema binario funciona assim','a comunicacao digital usa bits','conhecimento transforma nosso futuro','a criatividade resolve problemas complexos','explore os misterios da galaxia','a sustentabilidade protege o planeta','cada sequencia guarda informacoes','a matematica aparece em tudo','tecnologia e ciencia trabalham juntas']};
const tabela=Object.fromEntries([... 'abcdefghijklmnopqrstuvwxyz'].map(l=>[l,l.charCodeAt().toString(2).padStart(8,'0')]));tabela[' ']='00100000';
const e={menu:$('menu'),jogo:$('jogo'),carregamento:$('carregamento'),derrota:$('derrota'),resumoDerrota:$('resumoDerrota'),novo:$('jogarNovamente'),menuDerrota:$('menuDerrota'),placarDerrota:$('placarDerrota'),textoCarregamento:$('textoCarregamento'),nome:$('nomeJogador'),senha:$('senhaConta'),confirmar:$('confirmarSenha'),nomeEntrar:$('nomeEntrar'),senhaEntrar:$('senhaEntrar'),criar:$('criarContaBotao'),mostrarEntrar:$('mostrarEntrar'),mostrarCriar:$('mostrarCriar'),criarArea:$('criarConta'),entrarArea:$('entrarConta'),mensagem:$('mensagemConta'),entrar:$('entrarJogo'),placar:$('abrirPlacar'),como:$('abrirComo'),audioMenu:$('audioMenu'),audioJogo:$('audioJogo'),decoracoes:$('decoracoesMenu'),topo:$('jogadorTopo'),voltar:$('voltarMenu'),codigo:$('codigoBinario'),resp:$('resposta'),form:$('formResposta'),dica:$('botaoDica'),feedback:$('feedback'),nivel:$('nivelTexto'),pontos:$('pontos'),vidas:$('vidas'),seq:$('sequencia'),multi:$('multiplicador'),fala:$('falaRobo'),robo:$('robo'),lista:$('listaDescobertas'),alfa:$('botaoAlfabeto'),alfaC:$('conteudoAlfabeto'),tabela:$('tabelaAlfabeto'),sinal:$('botaoSinal'),codSinal:$('codigoSecreto'),formSinal:$('formSinal'),respSinal:$('respostaSinal'),resSinal:$('resultadoSinal'),estado:$('estadoMissao'),modal:$('modal'),modalC:$('conteudoModal'),fechar:$('fecharModal'),aviso:$('avisoFase'),subAviso:$('subAviso'),volume:$('volumeGeral'),valor:$('valorVolume'),musica:$('botaoMusica'),efeitos:$('botaoEfeitos'),voz:$('botaoVoz')};
let jogador=localStorage.getItem('binoJogador')||'',pontos=0,vidas=3,sequencia=0,melhorSequencia=0,atual='',ultimo='',dicas=0,missao=null,ctx,master,efeitos=true,voz=true,ligada=false,temporizador,temporizadorFala,temporizadorCodigo,fraseAtual='',indiceFala=0,estadoTela='menu',partidaEncerrada=false,niveisRecentes=[],perguntasDaPartida=0,temporizadoresMenu=[];
e.musicaMenu={textContent:'',onclick:null};
function binario(t){return [...t].map(x=>tabela[x]).join(' ')}function limpar(x){return x.trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function ocultarTodasAsTelas(){[e.menu,e.jogo,e.carregamento,e.derrota].forEach(t=>t.hidden=true);window.scrollTo(0,0)}
function ajustarRolagem(){document.body.classList.toggle('sem-rolagem',estadoTela==='carregamento')}
function mostrarMenu(){estadoTela='menu';ocultarTodasAsTelas();e.menu.hidden=false;ajustarRolagem();pausarFaixa(e.audioJogo);if(ligada)tocarFaixa(e.audioMenu);criarDecoracoesMenu()}
function mostrarCarregamento(){estadoTela='carregamento';ocultarTodasAsTelas();e.carregamento.hidden=false;ajustarRolagem();limparDecoracoesMenu()}
function atualizarEstadoMusica(){ligada=!e.audioJogo.paused;e.musica.textContent=`MÚSICA: ${ligada?'LIGADA':'DESLIGADA'}`}
function mostrarJogo(){estadoTela='jogo';ocultarTodasAsTelas();e.jogo.hidden=false;ajustarRolagem();if(ligada)tocarFaixa(e.audioJogo);setTimeout(atualizarEstadoMusica,180)}
function tocarFaixa(faixa){const outra=faixa===e.audioMenu?e.audioJogo:e.audioMenu;pausarFaixa(outra);faixa.volume=0;faixa.play().then(()=>fadeAudio(faixa,.18,800)).catch(()=>{e.feedback&&(e.feedback.textContent='Clique em MÚSICA para ativar a trilha sonora.')})}
function pausarFaixa(faixa){fadeAudio(faixa,0,350,()=>{faixa.pause();faixa.currentTime=0})}
function fadeAudio(faixa,alvo,ms,finalizar){const inicio=faixa.volume,passos=18,delta=(alvo-inicio)/passos;let i=0;const id=setInterval(()=>{faixa.volume=Math.max(0,Math.min(1,faixa.volume+delta));if(++i>=passos){clearInterval(id);faixa.volume=alvo;if(finalizar)finalizar()}},ms/passos)}
function criarDecoracoesMenu(){if(e.decoracoes.childElementCount)return;const guia=document.createElement('div');guia.className='guia-menu';guia.innerHTML='<div class="bino-menu-grande"><span></span><span></span><b></b></div><div id="falaMenuBino" class="fala-menu-bino">Oi! Eu sou o B.I.N.O. Vamos decifrar mensagens juntos?</div>';e.menu.querySelector('.menu-cartao').before(guia);['0','1','01','10','001','101','0','1'].forEach((bit,i)=>{const x=document.createElement('i');x.className='bit-solto';x.textContent=bit;x.style.left=`${Math.random()*92}%`;x.style.top=`${Math.random()*90}%`;x.style.setProperty('--d',`${6+i%5}s`);e.decoracoes.append(x)});const surgir=tipo=>{if(estadoTela!=='menu')return;const x=document.createElement('i');x.className=tipo;x.style.top=`${10+Math.random()*74}%`;if(Math.random()>.5){x.style.left='auto';x.style.right='-45px';x.style.transform='scaleX(-1)'}e.decoracoes.append(x);setTimeout(()=>x.remove(),tipo==='nave-menu'?4500:6500);temporizadoresMenu.push(setTimeout(()=>surgir(tipo),8000+Math.random()*12000))};surgir('robo-espreita');surgir('nave-menu')}
function limparDecoracoesMenu(){temporizadoresMenu.forEach(clearTimeout);temporizadoresMenu=[];e.decoracoes.innerHTML='';e.menu.querySelector('.guia-menu')?.remove()}
function audio(){if(!ctx){ctx=new (window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.gain.value=.55;master.connect(ctx.destination)}ctx.resume()}
function tom(n,d=.1,t='square',v=.06,a=0,forcar=false){if(!efeitos&&!forcar||!ctx)return;let o=ctx.createOscillator(),g=ctx.createGain(),i=ctx.currentTime+a;o.type=t;o.frequency.value=n;g.gain.setValueAtTime(.001,i);g.gain.exponentialRampToValueAtTime(v,i+.01);g.gain.exponentialRampToValueAtTime(.001,i+d);o.connect(g).connect(master);o.start(i);o.stop(i+d+.03)}
function clique(){audio();tom(560,.05)}
function bipBino(letra){if(!voz||!efeitos||letra===' '||!/[a-zà-ú0-9]/i.test(letra))return;audio();tom(510+(letra.charCodeAt(0)%7)*38,.026,'square',.018)}
function mostrarCodigoGradual(codigo){clearTimeout(temporizadorCodigo);e.codigo.textContent='';let i=0;const escrever=()=>{if(i>=codigo.length)return;const caractere=codigo[i++];e.codigo.textContent+=caractere;if(caractere==='0'||caractere==='1'){audio();tom(420+(i%6)*34,.018,'square',.012)}temporizadorCodigo=setTimeout(escrever,caractere===' '?42:24)};escrever()}
function concluirFala(){clearTimeout(temporizadorFala);e.fala.textContent=fraseAtual;e.robo.classList.remove('falando');indiceFala=fraseAtual.length}
function expressaoBino(tipo,duracao=900){e.robo.classList.remove('feliz','confuso','preocupado','surpreso','pensativo','orgulhoso','sonolento');if(tipo)e.robo.classList.add(tipo);if(duracao)setTimeout(()=>e.robo.classList.remove(tipo),duracao)}
function falar(t){clearTimeout(temporizadorFala);fraseAtual=t;indiceFala=0;e.fala.textContent='';e.robo.classList.add('falando');const escrever=()=>{if(indiceFala>=fraseAtual.length){e.robo.classList.remove('falando');return}const letra=fraseAtual[indiceFala++];e.fala.textContent+=letra;bipBino(letra);temporizadorFala=setTimeout(escrever,letra===' ' ? 42 : /[.!?,:]/.test(letra) ? 72 : 28)};escrever()}
function musica(){audio();if(temporizador)return;let notas=[262,330,392,330,294,349,440,349],i=0;let tocar=()=>{if(!ligada)return;let o=ctx.createOscillator(),g=ctx.createGain();o.type='square';o.frequency.value=notas[i++%notas.length]/2;g.gain.setValueAtTime(.001,ctx.currentTime);g.gain.linearRampToValueAtTime(.025,ctx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.28);o.connect(g).connect(master);o.start();o.stop(ctx.currentTime+.3);temporizador=setTimeout(tocar,360)};tocar()}
function atualizar(){e.pontos.textContent=String(pontos).padStart(3,'0');e.vidas.textContent='♥ '.repeat(vidas)+'♡ '.repeat(3-vidas);e.seq.textContent=sequencia;e.multi.textContent=`x${sequencia>=4?3:sequencia>=2?2:1}`}
function dificuldade(){if(perguntasDaPartida<3)return'facil';const opcoes=['facil','medio','dificil'].filter(n=>niveisRecentes.slice(-2).filter(x=>x===n).length<2);const nivel=opcoes[Math.floor(Math.random()*opcoes.length)];niveisRecentes.push(nivel);return nivel}function gerarPuzzleAleatorio(){let nivel=dificuldade(),lista=palavras[nivel].filter(t=>{let n=t.split(' ').length;return nivel==='facil'?n===1:nivel==='medio'?n>=2&&n<=3:n>=3&&n<=4}),opcoes=lista.filter(x=>x!==ultimo);atual=opcoes[Math.floor(Math.random()*opcoes.length)];ultimo=atual;perguntasDaPartida++;dicas=0;mostrarCodigoGradual(binario(atual));e.resp.value='';e.nivel.textContent=nivel.toUpperCase();e.feedback.textContent='Decifre a mensagem usando o alfabeto abaixo.';e.resp.focus();if(sequencia&&sequencia%5===0&&!missao)liberarTransmissaoOculta()}
function iniciarJogo(){jogador=limpar(e.nome.value)||jogador;if(!jogador){e.nome.focus();return}clique();localStorage.setItem('binoJogador',jogador);e.topo.textContent=jogador;pontos=0;vidas=3;sequencia=0;melhorSequencia=0;missao=null;perguntasDaPartida=0;niveisRecentes=[];partidaEncerrada=false;e.lista.innerHTML='<p class="vazio">Suas descobertas aparecerão aqui.</p>';e.codSinal.textContent='Avance cinco acertos para detectar um sinal.';e.estado.textContent='BÔNUS';atualizar();gerarPuzzleAleatorio();pausarFaixa(e.audioMenu);mostrarCarregamento();const mensagens=['PREPARANDO TRANSMISSÃO...','CONECTANDO AO SISTEMA BINÁRIO...','B.I.N.O. ESTÁ CALIBRANDO OS SENSORES...'];let i=0;const ciclo=setInterval(()=>{e.textoCarregamento.textContent=mensagens[++i%mensagens.length]},650);setTimeout(()=>{clearInterval(ciclo);mostrarJogo();expressaoBino('surpreso');falar(falaAleatoria('inicio'))},2300)}
function registrar(t){let x=document.createElement('div');x.className='descoberta';x.innerHTML=`<code>${binario(t)}</code> → <strong>${t}</strong>`;let v=e.lista.querySelector('.vazio');if(v)v.remove();e.lista.prepend(x)}
const falas={inicio:['Oi! Eu sou o B.I.N.O. Vamos decifrar mensagens juntos?','Ola, decodificador! Sua proxima descoberta comeca aqui.','Meus sensores estao prontos para uma nova aventura binaria!','Zero e um podem esconder coisas incriveis. Vamos descobrir?','Bem-vindo ao centro de transmissoes digitais!'],acerto:['Codigo decifrado! Excelente trabalho!','Perfeito! Voce encontrou a mensagem escondida.','Muito bem! Os bits fizeram sentido.','Incrivel! Continue assim, decodificador.','Acerto confirmado. Sua sequencia esta aumentando!'],erro:['Quase! Observe cada grupo de oito bits.','Um pequeno erro nao interrompe a missao.','Voce consegue! Cada tentativa ensina algo novo.','Essa transmissao ainda nao esta correta.'],vida:['Uma vida foi perdida, mas a missao continua.','Ainda temos chances. Continue decodificando!','Nao se preocupe, eu ainda acredito em voce.','Transmissao instavel, mas podemos recuperar.'],dica:['Vou deixar uma pista. Use seus sensores com cuidado!','Dica enviada. Analise a sequencia com calma.'],pular:['Tudo bem! Vamos procurar uma sequencia que combine mais com voce.','Pular tambem pode fazer parte da estrategia.','Nova sequencia a caminho. Continue tentando!','Voce nao desistiu, apenas escolheu outro desafio.','A missao continua! Vamos para outra transmissao.'],semDica:['Ainda precisamos de mais pontos para acessar essa dica.','Vamos conquistar alguns pontos antes de pedir ajuda.','Dica bloqueada por enquanto. Voce consegue tentar sozinho!'],semPular:['Ainda nao temos pontos suficientes para trocar esta sequencia.','Precisamos de 125 pontos para pular. Tente decifrar este sinal!','A reserva de pontos esta baixa, mas eu acredito em voce.','Pular exige energia digital. Conquiste mais pontos primeiro!'],fim:['A transmissao foi encerrada, mas voce aprendeu muito.','Voce chegou longe. Vamos voltar ainda mais preparados.']};let ultimaFala={};function falaAleatoria(tipo){let a=falas[tipo],op=a.filter(x=>x!==ultimaFala[tipo]);let x=op[Math.floor(Math.random()*op.length)];ultimaFala[tipo]=x;return x}
function verificarResposta(){if(partidaEncerrada)return;clique();if(limpar(e.resp.value)!==atual){perderVida();return}let m=sequencia>=4?3:sequencia>=2?2:1;sequencia++;melhorSequencia=Math.max(melhorSequencia,sequencia);pontos+=100*m;audio();[520,740,1040].forEach((n,i)=>tom(n,.15,'sine',.08,i*.1));e.robo.classList.add('comemorando');expressaoBino(sequencia>=5?'orgulhoso':'feliz');registrar(atual);e.feedback.className='acerto';e.feedback.textContent=`Correto! +${100*m} pontos`;falar(falaAleatoria('acerto'));atualizar();setTimeout(()=>{e.robo.classList.remove('comemorando');gerarPuzzleAleatorio()},700)}
function perderVida(){if(partidaEncerrada)return;audio();tom(210,.15,'triangle');tom(170,.13,'sine',.05,.1);vidas--;sequencia=0;e.robo.classList.add('triste');expressaoBino(vidas?'preocupado':'confuso');e.feedback.className='erro';e.feedback.textContent='Resposta incorreta. Você perdeu uma vida.';falar(vidas?falaAleatoria('vida'):falaAleatoria('fim'));atualizar();if(!vidas){partidaEncerrada=true;setTimeout(finalizarPartida,800)}else setTimeout(()=>{e.robo.classList.remove('triste');gerarPuzzleAleatorio()},700)}
function pedirDica(){if(pontos<25){e.feedback.className='erro';e.feedback.textContent='Pontos insuficientes para pedir dica.';expressaoBino('preocupado');falar(falaAleatoria('semDica'));return}if(!confirm('Esta dica custa 25 pontos. Deseja continuar?'))return;clique();expressaoBino('pensativo');pontos-=25;dicas++;let t=dicas===1?`A resposta tem ${atual.replaceAll(' ','').length} letras e ${atual.split(' ').length} palavra(s).`:dicas===2?`A primeira letra é “${atual[0]}”.`:`Começo da resposta: “${atual.slice(0,Math.ceil(atual.length/2))}...”`;e.feedback.textContent=`-25 pontos · ${t}`;atualizar();falar(`${falaAleatoria('dica')} ${t}`)}
function pularSequencia(){if(partidaEncerrada)return;if(pontos<125){e.feedback.className='erro';e.feedback.textContent='Pontos insuficientes para pular esta sequência.';expressaoBino('preocupado');falar(falaAleatoria('semPular'));return}if(!confirm('Pular esta sequência custa 125 pontos. Deseja continuar?'))return;pontos-=125;e.feedback.className='';e.feedback.textContent='-125 pontos · Sequência pulada.';expressaoBino('pensativo');atualizar();falar(falaAleatoria('pular'));gerarPuzzleAleatorio()}
function liberarTransmissaoOculta(){let op=['algoritmo secreto','mensagem digital','codigo misterioso','sistema inteligente','planeta desconhecido','ciencia e futuro','tecnologia criativa','biblioteca digital','universo infinito','o sinal chegou','decodifique esta mensagem','a transmissao e secreta','conhecimento muda tudo','o robot encontrou pistas','tecnologia conecta pessoas','descubra o codigo oculto'];missao=op[Math.floor(Math.random()*op.length)];e.codSinal.textContent=binario(missao);e.estado.textContent='NOVA';audio();[270,350,310,440].forEach((n,i)=>tom(n,.07,'square',.04,i*.11));expressaoBino('surpreso');falar('Uma transmissão oculta apareceu. Ela vale cento e cinquenta pontos extras!')}
function investigar(){if(!missao){e.resSinal.textContent='Nenhum sinal raro detectado ainda.';return}clique();e.formSinal.hidden=false;e.respSinal.focus()}
function verificarSinal(){if(limpar(e.respSinal.value)!==missao){e.resSinal.textContent='Ainda não foi decifrado. Você pode tentar novamente sem perder vidas.';return}pontos+=150;const ganhouVida=vidas<3;if(ganhouVida)vidas++;registrar(`transmissao oculta: ${missao}`);e.resSinal.textContent=`Transmissão decifrada! +150 pontos${ganhouVida?' · +1 coração':''}`;e.formSinal.hidden=true;e.estado.textContent='DECIFRADA';audio();[440,660,880,1040].forEach((n,i)=>tom(n,.12,'sine',.08,i*.09));missao=null;atualizar();falar('Transmissão oculta decifrada. Excelente descoberta!')}
function salvarPlacar(){let lista=JSON.parse(localStorage.getItem('binoPlacar')||'[]'),i=lista.findIndex(x=>x.nome===jogador),anterior=lista[i]||{},r={nome:jogador,pontos:Math.max(pontos,anterior.pontos||0),sequencia:Math.max(melhorSequencia,anterior.sequencia||0),partidas:(anterior.partidas||0)+1,ultimaPartida:new Date().toLocaleDateString('pt-BR')};if(i>=0)lista[i]=r;else lista.push(r);localStorage.setItem('binoPlacar',JSON.stringify(lista))}
function abrirModal(){if(!e.modalC.innerHTML.trim())return;e.modal.hidden=false;e.modal.setAttribute('aria-hidden','false');e.fechar.focus()}
function fecharModal(){e.modal.hidden=true;e.modal.setAttribute('aria-hidden','true')}
function roboMini(){return '<span class="robo-mini" aria-hidden="true"><i></i><i></i></span>'}
function mostrarPerfil(nome){const lista=JSON.parse(localStorage.getItem('binoPlacar')||'[]').sort((a,b)=>b.pontos-a.pontos),p=lista.find(x=>x.nome===nome);if(!p)return;const posicao=lista.indexOf(p)+1;e.modalC.innerHTML=`<h2 id="tituloModal">PERFIL DO JOGADOR</h2><div class="perfil-nome">${roboMini()} <b>${p.nome}</b></div><p><strong>Posição:</strong> ${posicao}º no placar local</p><p><strong>Maior pontuação:</strong> ${p.pontos||0}</p><p><strong>Melhor sequência:</strong> ${p.sequencia||0}</p><p><strong>Partidas realizadas:</strong> ${p.partidas||1}</p><p><strong>Última partida:</strong> ${p.ultimaPartida||'Não registrada'}</p>`;abrirModal()}
function mostrarPlacar(){let lista=JSON.parse(localStorage.getItem('binoPlacar')||'[]').sort((a,b)=>b.pontos-a.pontos);e.modalC.innerHTML=`<h2 id="tituloModal">PLACAR LOCAL</h2><p>Salvo somente neste navegador. Clique em um nome para ver o perfil.</p>${lista.length?`<ol class="ranking">${lista.map(x=>`<li>${roboMini()} <button class="nome-ranking" type="button" data-jogador="${x.nome}">${x.nome}</button><span>${x.pontos} pontos · sequência ${x.sequencia||0} · ${x.partidas||1} partida(s)</span></li>`).join('')}</ol>`:'<p>Nenhuma partida registrada ainda.</p>'}`;abrirModal();e.modalC.querySelectorAll('.nome-ranking').forEach(b=>b.onclick=()=>mostrarPerfil(b.dataset.jogador))}
function finalizarPartida(){if(!partidaEncerrada)return;salvarPlacar();audio();[330,260,196].forEach((n,i)=>tom(n,.24,'triangle',.08,i*.16));fecharModal();estadoTela='derrota';ocultarTodasAsTelas();e.derrota.hidden=false;ajustarRolagem();e.resumoDerrota.textContent=`Pontuação final: ${pontos} · melhor sequência: ${melhorSequencia}`;falar('Fim de jogo. Você foi muito bem! Tente novamente para superar sua pontuação.')}
function renderAlfabeto(){e.tabela.innerHTML=[...'abcdefghijklmnopqrstuvwxyz '].map(l=>`<div class="letra-binaria"><strong>${l===' '?'espaço':l}</strong><code>${tabela[l]}</code></div>`).join('')}
e.entrar.onclick=iniciarJogo;e.form.onsubmit=x=>{x.preventDefault();verificarResposta()};e.dica.onclick=pedirDica;e.sinal.onclick=investigar;e.formSinal.onsubmit=x=>{x.preventDefault();verificarSinal()};e.alfa.onclick=()=>{let a=!e.alfaC.hidden;e.alfaC.hidden=a;e.alfa.setAttribute('aria-expanded',!a)};e.placar.onclick=mostrarPlacar;e.como.onclick=()=>{e.modalC.innerHTML='<h2 id="tituloModal">COMO JOGAR</h2><p>Consulte o alfabeto, decifre a palavra binária e mantenha suas três vidas. Cada acerto aumenta sua sequência e pontuação.</p>';abrirModal()};e.fechar.onclick=fecharModal;e.modal.onclick=x=>{if(x.target===e.modal)fecharModal()};document.addEventListener('keydown',x=>{if(x.key==='Escape'&&!e.modal.hidden)fecharModal();if(x.key==='Enter'&&indiceFala<fraseAtual.length)concluirFala()});e.fala.onclick=concluirFala;e.fala.onkeydown=x=>{if(x.key==='Enter'||x.key===' '){x.preventDefault();concluirFala()}};e.voltar.onclick=()=>{mostrarMenu();falar('Voltamos ao menu. Estarei aqui quando você quiser uma nova missão.')};e.volume.oninput=()=>{audio();master.gain.value=e.volume.value/100;[e.audioMenu,e.audioJogo].forEach(a=>{if(!a.paused)a.volume=Math.min(.25,e.volume.value/100*.25)});e.valor.textContent=`${e.volume.value}%`};function alternarMusica(){ligada=!ligada;e.musica.textContent=`MÚSICA: ${ligada?'LIGADA':'DESLIGADA'}`;e.musicaMenu.textContent=`MÚSICA: ${ligada?'LIGADA':'DESLIGADA'}`;if(ligada){tocarFaixa(estadoTela==='menu'?e.audioMenu:e.audioJogo)}else{pausarFaixa(e.audioMenu);pausarFaixa(e.audioJogo)}}e.musica.onclick=alternarMusica;e.musicaMenu.onclick=alternarMusica;e.efeitos.onclick=()=>{efeitos=!efeitos;e.efeitos.textContent=`EFEITOS: ${efeitos?'LIGADOS':'DESLIGADOS'}`};e.voz.onclick=()=>{voz=!voz;e.voz.textContent=`SOM B.I.N.O.: ${voz?'LIGADO':'DESLIGADO'}`};e.nome.value=jogador;renderAlfabeto();mostrarMenu();
/* B.I.N.O. interativo no menu e carregamento sem transmissao antecipada. */
let temporizadorFalaMenu=0,indiceFalaMenu=0,fraseMenuAtual='',ultimoToqueMenu=0;
const falasMenu={toque:['Yowch!','Owch!','Ei, cuidado!','Pare, minhas engrenagens fazem cosquinha!','Hehe! Isso me surpreendeu.','Meus sensores sentiram isso!','B.I.N.O. ainda esta inteiro!','Clique gentilmente, decodificador!'],criar:['Vamos criar sua identidade digital!','Escolha um nome que combine com um grande decodificador.','Sua conta vai ficar salva neste dispositivo.','Quase pronto para uma nova missao!'],entrar:['Bem-vindo de volta, decodificador!','Vamos verificar seus dados digitais.','Seus sinais parecem familiares.','Preparando o acesso a sua conta.'],placar:['Vamos ver quem dominou mais sequencias!','O placar guarda grandes descobertas.','Talvez seu nome apareca no topo em breve!','Cada ponto conta nessa missao.'],como:['Eu explico tudo! E mais simples do que parece.','Bits, letras e descobertas: esse e o plano.','Use o alfabeto binario como seu mapa.','Vamos transformar zeros e uns em palavras.'],erro:['Hmm... esses dados nao parecem corretos.','Confira o nome e a senha com calma.','Meus sensores encontraram uma pequena falha.','Nada de panico, tente novamente.']};
const ultimaFalaMenu={};
const boasVindasMenu=['Oi! Eu sou o B.I.N.O. Vamos decifrar algo hoje?','Ola, decodificador! Meus sensores estavam esperando por voce.','Bem-vindo ao centro de transmissoes binarias!','Oi! Preparado para transformar bits em descobertas?','Que bom ver voce por aqui! Vamos comecar uma missao?','Saudacoes, decodificador. O sistema esta pronto!','B.I.N.O. online! Qual sera a proxima descoberta?','Oi! Zeros e uns escondem muitas surpresas.'];
let ultimaBoasVindasMenu='',interacaoAudioMenu=false;
function saudarMenu(){const opcoes=boasVindasMenu.filter(f=>f!==ultimaBoasVindasMenu);ultimaBoasVindasMenu=opcoes[Math.floor(Math.random()*opcoes.length)];falarMenu(ultimaBoasVindasMenu)}
function somToqueBinoMenu(){if(!interacaoAudioMenu||!efeitos)return;audio();tom(460,.055,'sine',.035);tom(690,.075,'triangle',.028,.045)}
document.addEventListener('pointerdown',()=>{interacaoAudioMenu=true},{once:true,capture:true});
document.addEventListener('keydown',()=>{interacaoAudioMenu=true},{once:true,capture:true});
function falaMenuAleatoria(tipo){const opcoes=falasMenu[tipo]||falasMenu.toque;const novas=opcoes.filter(f=>f!==ultimaFalaMenu[tipo]);const fala=novas[Math.floor(Math.random()*novas.length)];ultimaFalaMenu[tipo]=fala;return fala}
function concluirFalaMenu(){clearTimeout(temporizadorFalaMenu);const alvo=document.getElementById('falaMenuBino');if(alvo)alvo.textContent=fraseMenuAtual;indiceFalaMenu=fraseMenuAtual.length;document.querySelector('.bino-menu-grande')?.classList.remove('falando-menu')}
function falarMenu(texto){const alvo=document.getElementById('falaMenuBino');if(!alvo)return;clearTimeout(temporizadorFalaMenu);fraseMenuAtual=texto;indiceFalaMenu=0;alvo.textContent='';const roboMenu=document.querySelector('.bino-menu-grande');roboMenu?.classList.add('falando-menu');const escrever=()=>{if(indiceFalaMenu>=fraseMenuAtual.length){roboMenu?.classList.remove('falando-menu');return}const letra=fraseMenuAtual[indiceFalaMenu++];alvo.textContent+=letra;if(interacaoAudioMenu)bipBino(letra);temporizadorFalaMenu=setTimeout(escrever,letra===' '?32:/[,.!?]/.test(letra)?55:26)};escrever()}
function prepararBinoMenu(){const roboMenu=document.querySelector('.bino-menu-grande'),balao=document.getElementById('falaMenuBino');if(!roboMenu||roboMenu.dataset.pronto)return;roboMenu.dataset.pronto='true';roboMenu.setAttribute('role','button');roboMenu.setAttribute('tabindex','0');roboMenu.setAttribute('aria-label','Conversar com B.I.N.O.');if(balao){balao.setAttribute('role','button');balao.setAttribute('tabindex','0');balao.setAttribute('aria-label','Mostrar a fala completa do B.I.N.O.');balao.addEventListener('click',concluirFalaMenu);balao.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();concluirFalaMenu()}})}const reagir=()=>{if(Date.now()-ultimoToqueMenu<450)return;ultimoToqueMenu=Date.now();somToqueBinoMenu();roboMenu.classList.remove('tocando-menu');void roboMenu.offsetWidth;roboMenu.classList.add('tocando-menu');falarMenu(falaMenuAleatoria('toque'))};roboMenu.addEventListener('click',reagir);roboMenu.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();reagir()}})}
const criarDecoracoesMenuAnterior=criarDecoracoesMenu;
criarDecoracoesMenu=function(){criarDecoracoesMenuAnterior();prepararBinoMenu()};
const mostrarMenuAnterior=mostrarMenu;
mostrarMenu=function(){clearTimeout(temporizadorCodigo);clearTimeout(temporizadorFalaMenu);mostrarMenuAnterior();prepararBinoMenu();saudarMenu()};
const mostrarCarregamentoAnterior=mostrarCarregamento;
mostrarCarregamento=function(){clearTimeout(temporizadorCodigo);if(e.codigo)e.codigo.textContent='';mostrarCarregamentoAnterior()};
const finalizarPartidaAnterior=finalizarPartida;
finalizarPartida=function(){clearTimeout(temporizadorCodigo);finalizarPartidaAnterior()};
function liberarMusicaJogo(){if(!ligada)return;e.audioJogo.pause();e.audioJogo.currentTime=0;e.audioJogo.volume=0;const tentativa=e.audioJogo.play();if(tentativa&&tentativa.catch)tentativa.catch(()=>{})}
const mostrarJogoAnterior=mostrarJogo;
mostrarJogo=function(){if(!e.audioJogo.paused)e.audioJogo.currentTime=0;mostrarJogoAnterior()};
function iniciarJogo(){jogador=limpar(e.nome.value)||jogador;if(!jogador){e.nome.focus();return}clearTimeout(temporizadorCodigo);clearTimeout(temporizadorFalaMenu);clique();liberarMusicaJogo();localStorage.setItem('binoJogador',jogador);e.topo.textContent=jogador;pontos=0;vidas=3;sequencia=0;melhorSequencia=0;missao=null;perguntasDaPartida=0;niveisRecentes=[];partidaEncerrada=false;e.lista.innerHTML='<p class="vazio">Suas descobertas aparecerao aqui.</p>';e.codSinal.textContent='Avance cinco acertos para detectar um sinal.';e.estado.textContent='BONUS';e.codigo.textContent='';e.resp.value='';atualizar();pausarFaixa(e.audioMenu);mostrarCarregamento();const mensagens=['PREPARANDO TRANSMISSAO...','CONECTANDO AO SISTEMA BINARIO...','B.I.N.O. ESTA CALIBRANDO OS SENSORES...'];let indice=0;clearInterval(window.cicloCarregamentoBino);window.cicloCarregamentoBino=setInterval(()=>{e.textoCarregamento.textContent=mensagens[++indice%mensagens.length]},650);clearTimeout(window.tempoCarregamentoBino);window.tempoCarregamentoBino=setTimeout(()=>{clearInterval(window.cicloCarregamentoBino);mostrarJogo();gerarPuzzleAleatorio();expressaoBino('surpreso');falar(falaAleatoria('inicio'))},2300)}
function contas(){return JSON.parse(localStorage.getItem('binoContas')||'{}')}
const falasInteracaoPartida=['Ei! Estou analisando cada bit com voce.','Meus sensores estao atentos!','Nao deixe essa sequencia te confundir.','Voce consegue decifrar isso!','Zeros e uns formam grandes descobertas.','Estou aqui para ajudar, decodificador.','Essa transmissao parece interessante.','B.I.N.O. continua online!','Toque gentilmente nos meus circuitos!','Yowch! Meus sensores fizeram cosquinha!','Owch! Mas eu ainda estou funcionando.','Hehe! Isso foi inesperado.'];
let ultimaInteracaoPartida='',ultimoToqueBinoPartida=0;
function falaInteracaoPartida(){const opcoes=falasInteracaoPartida.filter(f=>f!==ultimaInteracaoPartida);const fala=opcoes[Math.floor(Math.random()*opcoes.length)];ultimaInteracaoPartida=fala;return fala}
function somToqueBinoPartida(){if(!efeitos)return;audio();tom(470,.055,'sine',.035);tom(660,.07,'triangle',.027,.045)}
function prepararBinoPartida(){if(!e.robo||e.robo.dataset.interativo)return;e.robo.dataset.interativo='true';e.robo.setAttribute('role','button');e.robo.setAttribute('tabindex','0');e.robo.setAttribute('aria-label','Conversar com B.I.N.O.');const reagir=()=>{if(Date.now()-ultimoToqueBinoPartida<450)return;ultimoToqueBinoPartida=Date.now();somToqueBinoPartida();e.robo.classList.remove('toque-partida');void e.robo.offsetWidth;e.robo.classList.add('toque-partida');setTimeout(()=>e.robo.classList.remove('toque-partida'),650);expressaoBino('surpreso',650);falar(falaInteracaoPartida())};e.robo.addEventListener('click',reagir);e.robo.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();reagir()}})}
prepararBinoPartida();
function prepararBinoMenu(){const roboMenu=document.querySelector('.bino-menu-grande'),balao=document.getElementById('falaMenuBino');if(!roboMenu)return;if(!roboMenu.dataset.modeloBino){roboMenu.dataset.modeloBino='true';roboMenu.innerHTML='<span class="bino-antena"><i></i></span><span class="bino-cabeca"><i class="bino-olho"></i><i class="bino-olho"></i><i class="bino-boca"></i></span><strong class="bino-corpo">BINO</strong><i class="bino-anel"></i>'}if(roboMenu.dataset.pronto)return;roboMenu.dataset.pronto='true';roboMenu.setAttribute('role','button');roboMenu.setAttribute('tabindex','0');roboMenu.setAttribute('aria-label','Conversar com B.I.N.O.');if(balao){balao.setAttribute('role','button');balao.setAttribute('tabindex','0');balao.setAttribute('aria-label','Mostrar a fala completa do B.I.N.O.');balao.addEventListener('click',concluirFalaMenu);balao.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();concluirFalaMenu()}})}const reagir=()=>{if(Date.now()-ultimoToqueMenu<450)return;ultimoToqueMenu=Date.now();somToqueBinoMenu();roboMenu.classList.remove('tocando-menu');void roboMenu.offsetWidth;roboMenu.classList.add('tocando-menu');falarMenu(falaMenuAleatoria('toque'))};roboMenu.addEventListener('click',reagir);roboMenu.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();reagir()}})}
prepararBinoMenu();saudarMenu();
const mensagemContaAnterior=mensagemConta;
mensagemConta=function(texto,sucesso=false){mensagemContaAnterior(texto,sucesso);if(!sucesso)falarMenu(falaMenuAleatoria('erro'))};
e.criar.addEventListener('focus',()=>falarMenu(falaMenuAleatoria('criar')));
e.criar.addEventListener('click',()=>falarMenu(falaMenuAleatoria('criar')));
e.mostrarEntrar.addEventListener('click',()=>falarMenu(falaMenuAleatoria('entrar')));
e.mostrarCriar.addEventListener('click',()=>falarMenu(falaMenuAleatoria('criar')));
e.placar.addEventListener('click',()=>falarMenu(falaMenuAleatoria('placar')));
e.como.addEventListener('click',()=>falarMenu(falaMenuAleatoria('como')));
function mensagemConta(t,sucesso=false){const alvo=e.criarArea.hidden?e.senhaEntrar:e.confirmar;e.mensagem.remove();alvo.insertAdjacentElement('afterend',e.mensagem);e.mensagem.textContent=t;e.mensagem.className=sucesso?'mensagem-conta sucesso':'mensagem-conta'}
function criarConta(){const nome=limpar(e.nome.value),senha=e.senha.value,c=contas();if(!nome||senha.length<4||senha!==e.confirmar.value){mensagemConta('Preencha os dados. A senha deve ter ao menos 4 caracteres e coincidir.');return}if(c[nome]){mensagemConta('Este nome de usuário já foi usado neste navegador. Escolha outro nome.');return}c[nome]={senha};localStorage.setItem('binoContas',JSON.stringify(c));mensagemConta('Conta criada! Agora entre com seus dados.',true);e.nomeEntrar.value=nome;e.criarArea.hidden=true;e.entrarArea.hidden=false}
function entrarConta(){const nome=limpar(e.nomeEntrar.value),c=contas();if(!c[nome]||c[nome].senha!==e.senhaEntrar.value){mensagemConta('Nome de usuário ou senha incorretos.');return}jogador=nome;e.nome.value=nome;partidaEncerrada=false;iniciarJogo()}
e.criar.onclick=criarConta;e.entrar.onclick=entrarConta;e.mostrarEntrar.onclick=()=>{e.criarArea.hidden=true;e.entrarArea.hidden=false;e.mensagem.textContent=''};e.mostrarCriar.onclick=()=>{e.entrarArea.hidden=true;e.criarArea.hidden=false;e.mensagem.textContent=''};e.novo.onclick=()=>{partidaEncerrada=false;iniciarJogo()};e.menuDerrota.onclick=()=>{partidaEncerrada=false;mostrarMenu()};e.placarDerrota.onclick=mostrarPlacar;e.audioJogo.addEventListener('play',atualizarEstadoMusica);e.audioJogo.addEventListener('pause',atualizarEstadoMusica);e.como.onclick=()=>{e.modalC.innerHTML='<h2 id="tituloModal">COMO JOGAR</h2><p>Transforme bits em palavras e mantenha a transmissao ativa.</p><div class="passos-como"><div><b>1.</b> Consulte o Alfabeto Binario.</div><div><b>2.</b> Leia grupos de 8 bits.</div><div><b>3.</b> Digite a palavra ou frase.</div><div><b>4.</b> Acerte para ganhar pontos.</div><div><b>5.</b> Proteja seus 3 coracoes.</div><div><b>6.</b> Use dica ou pular com estrategia.</div><div><b>7.</b> Resolva Transmissoes Ocultas para bonus.</div></div>';abrirModal()};document.querySelectorAll('button').forEach(b=>{let ultimo=0;b.addEventListener('pointerenter',()=>{if(Date.now()-ultimo<130)return;ultimo=Date.now();audio();tom(760,.025,'sine',.018)});b.addEventListener('click',()=>{audio();tom(540,.05,'square',.04)})});document.addEventListener('pointerdown',()=>{if(estadoTela==='menu'&&!ligada){ligada=true;tocarFaixa(e.audioMenu)}},{once:true});
const botaoPular=document.createElement('button');botaoPular.id='botaoPular';botaoPular.className='botao-secundario';botaoPular.type='button';botaoPular.textContent='↷ PULAR (-125)';e.dica.insertAdjacentElement('afterend',botaoPular);botaoPular.addEventListener('click',pularSequencia);

/* Controle confiavel das duas faixas: o botao nao depende de uma musica pausada em outra tela. */
function atualizarEstadoMusica(){const texto=`MÚSICA: ${ligada?'LIGADA':'DESLIGADA'}`;e.musica.textContent=texto;e.musicaMenu.textContent=texto}
function fadeAudio(faixa,alvo,ms=500,finalizar){clearInterval(faixa._fadeBino);const inicio=Number(faixa.volume)||0,passos=16,delta=(alvo-inicio)/passos;let passo=0;faixa._fadeBino=setInterval(()=>{faixa.volume=Math.max(0,Math.min(1,faixa.volume+delta));if(++passo>=passos){clearInterval(faixa._fadeBino);faixa.volume=alvo;if(finalizar)finalizar()}},ms/passos)}
function pausarFaixa(faixa){clearInterval(faixa._fadeBino);if(faixa.paused){faixa.volume=0;return}fadeAudio(faixa,0,350,()=>{faixa.pause();faixa.currentTime=0})}
function tocarFaixa(faixa){const outra=faixa===e.audioMenu?e.audioJogo:e.audioMenu;pausarFaixa(outra);clearInterval(faixa._fadeBino);faixa.volume=0;const inicio=faixa.play();if(inicio&&inicio.then)inicio.then(()=>{if(ligada)fadeAudio(faixa,.18,700)}).catch(()=>{if(e.feedback)e.feedback.textContent='Não foi possível iniciar esta música. Verifique o arquivo de áudio.'})}
function alternarMusica(){ligada=!ligada;atualizarEstadoMusica();if(ligada){tocarFaixa(estadoTela==='menu'?e.audioMenu:e.audioJogo)}else{pausarFaixa(e.audioMenu);pausarFaixa(e.audioJogo)}}
function mostrarJogo(){estadoTela='jogo';ocultarTodasAsTelas();e.jogo.hidden=false;ajustarRolagem();if(ligada)tocarFaixa(e.audioJogo);atualizarEstadoMusica()}
e.musica.onclick=alternarMusica;e.musicaMenu.onclick=alternarMusica;
e.audioJogo.addEventListener('error',()=>{if(e.feedback)e.feedback.textContent='A música da partida não foi encontrada.'});

/* A faixa e autorizada no clique e revelada apenas quando o carregamento termina. */
let musicaPartidaPreparada=false;
function liberarMusicaJogo(){musicaPartidaPreparada=false;if(!ligada)return;e.audioJogo.pause();e.audioJogo.currentTime=0;e.audioJogo.muted=true;e.audioJogo.volume=0;const inicio=e.audioJogo.play();if(inicio&&inicio.then)inicio.then(()=>{musicaPartidaPreparada=true}).catch(()=>{musicaPartidaPreparada=false;if(e.feedback)e.feedback.textContent='Clique em MÚSICA para permitir a trilha da partida.'})}
function mostrarJogo(){estadoTela='jogo';ocultarTodasAsTelas();e.jogo.hidden=false;ajustarRolagem();if(!ligada){atualizarEstadoMusica();return}pausarFaixa(e.audioMenu);const revelar=()=>{e.audioJogo.muted=false;fadeAudio(e.audioJogo,.18,700)};if(musicaPartidaPreparada&&!e.audioJogo.paused){revelar()}else{e.audioJogo.volume=0;e.audioJogo.muted=false;const inicio=e.audioJogo.play();if(inicio&&inicio.then)inicio.then(revelar).catch(()=>{if(e.feedback)e.feedback.textContent='Não foi possível iniciar a música da partida.'})}atualizarEstadoMusica()}
